/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * payment-systems API
 * OpenAPI spec version: 0.0.1
 */
import type { SubscriptionResponse } from './subscriptionResponse';

export interface GetMeResponse {
  /** User ID */
  id: string;
  /** User full name */
  name: string;
  /** User email address */
  email: string;
  /** Whether auto-renewal is enabled */
  isAutoRenewal: boolean;
  subscription?: SubscriptionResponse;
}
