/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * payment-systems API
 * OpenAPI spec version: 0.0.1
 */

export interface InitPaymentResponse {
  /** URL to redirect the user to the selected payment provider */
  url: string;
}
