/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * payment-systems API
 * OpenAPI spec version: 0.0.1
 */

/**
 * The payment provider used for the transaction
 */
export type PaymentHistoryResponseProvider = typeof PaymentHistoryResponseProvider[keyof typeof PaymentHistoryResponseProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentHistoryResponseProvider = {
  YOOKASSA: 'YOOKASSA',
  STRIPE: 'STRIPE',
  CRYPTOPAY: 'CRYPTOPAY',
} as const;
