/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * payment-systems API
 * OpenAPI spec version: 0.0.1
 */
import type { PaymentHistoryResponseProvider } from './paymentHistoryResponseProvider';
import type { PaymentHistoryResponseStatus } from './paymentHistoryResponseStatus';

export interface PaymentHistoryResponse {
  /** Payment ID */
  id: string;
  /** Transaction creation date */
  createdAt: string;
  /** Tariff plan name */
  plan: string;
  /** Transaction amount */
  amount: number;
  /** The payment provider used for the transaction */
  provider: PaymentHistoryResponseProvider;
  /** Transaction status */
  status: PaymentHistoryResponseStatus;
}
