/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * payment-systems API
 * OpenAPI spec version: 0.0.1
 */

export interface PlansResponse {
  /** Unique plan ID */
  id: string;
  /** Tariff plan name */
  title: string;
  /** Full access to ... */
  description: string;
  /** Features available in the tariff plan */
  features: string[];
  /** Monthly price */
  monthlyPrice: number;
  /** Early price */
  yearlyPrice: number;
  /** Indicates whether the tariff plan is popular */
  isPopular: boolean;
}
