/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * payment-systems API
 * OpenAPI spec version: 0.0.1
 */

export interface PlanInfo {
  /** Unique plan ID */
  id: string;
  /** Tariff plan name */
  title: string;
  /** Monthly price */
  monthlyPrice: number;
  /** Yearly price */
  yearlyPrice: number;
}
