/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * payment-systems API
 * OpenAPI spec version: 0.0.1
 */
import type { SubscriptionResponseStatus } from './subscriptionResponseStatus';
import type { PlansResponse } from './plansResponse';

export interface SubscriptionResponse {
  /** Current subscription status */
  status: SubscriptionResponseStatus;
  /** Subscription start date */
  startDate: string;
  /** Subscription end date */
  endDate: string;
  plan: PlansResponse;
}
