/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * payment-systems API
 * OpenAPI spec version: 0.0.1
 */
import type { PlanInfo } from './planInfo';

export interface SubscriptionInfo {
  /** Detailed information about the selected tariff plan */
  plan: PlanInfo;
}
