/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * payment-systems API
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateAutoRenewalResponse {
  /** Enable or disable auto-renewal */
  isAutoRenewal: boolean;
}
